package service

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"

	"github.com/lukasstrickler/noto/internal/platform/config"
	"github.com/lukasstrickler/noto/internal/transport/notoapi"
)

const (
	modalProviderID          = "modal"
	modalDesiredVersion      = "noto-modal-compute.v1"
	modalUserDataPolicy      = "user audio defaults to http/temporary modal.Volume.ephemeral transport; permanent named Volumes are explicit opt-in and must be cleaned"
	modalBenchmarkDataPolicy = "benchmark corpora may use the dedicated permanent benchmark Volume; temporary/http remain available for smoke runs"
	modalModelDataPolicy     = "model weights are cached separately from user audio and loaded from the configured cache, never downloaded during each inference request"
)

// GetModalComputeStatus reports whether this backend is configured to offload
// STT/diarization to a user-owned Modal Web Function. It deliberately does not
// infer a Modal URL; free-plan endpoints are generated by Modal and must come
// from setup/deploy discovery or user config.
func (s *Service) GetModalComputeStatus(ctx context.Context) (notoapi.ModalStatus, error) {
	cfg := s.currentCfg()
	m := modalDefaults(cfg.Compute.Modal)
	cred, _ := s.secretStatus(ctx, m.TokenRef)
	epCred, _ := s.secretStatus(ctx, m.EndpointTokenRef)
	ready := strings.TrimSpace(m.EndpointURL) != ""
	return notoapi.ModalStatus{
		Configured:             cfg.Compute.Provider == modalProviderID || ready || cred.Configured,
		Ready:                  ready,
		Provider:               modalProviderID,
		AppName:                m.AppName,
		Environment:            m.Environment,
		GPU:                    m.GPU,
		EndpointURL:            m.EndpointURL,
		CredentialSource:       cred.Source,
		EndpointTokenSource:    epCred.Source,
		DeploymentVersion:      m.DeploymentVersion,
		DesiredVersion:         modalDesiredVersion,
		NeedsUpdate:            m.DeploymentVersion != "" && m.DeploymentVersion != modalDesiredVersion,
		UserDataPolicy:         modalUserDataPolicy,
		BenchmarkDataPolicy:    modalBenchmarkDataPolicy,
		ModelDataPolicy:        modalModelDataPolicy,
		UserTransferMode:       m.UserTransferMode,
		BenchmarkTransferMode:  m.BenchmarkTransferMode,
		TemporaryThresholdMB:   m.TemporaryThresholdMB,
		ScaledownWindowSeconds: m.ScaledownWindowSeconds,
		MinContainers:          m.MinContainers,
		ModelCache:             m.ModelCache,
		LargeFileTransferMode:  "temporary = modal.Volume.ephemeral; permanent = named modal.Volume; http = Web Function request body",
		Message:                modalStatusMessage(ready, m.DeploymentVersion),
	}, nil
}

// SetupModalCompute persists Modal credentials/metadata and optionally points
// speech+diarization at the configured endpoint. It never shells out to Modal
// CLI/Python and never creates user-audio volumes. EndpointURL is required for
// Ready=true until an official in-process deploy/discovery client is wired.
func (s *Service) SetupModalCompute(ctx context.Context, req notoapi.ModalSetupRequest) (notoapi.ModalStatus, error) {
	m := modalDefaults(config.ModalComputeConfig{
		AppName:                req.AppName,
		Environment:            req.Environment,
		GPU:                    req.GPU,
		EndpointURL:            strings.TrimSpace(req.EndpointURL),
		TokenRef:               config.ModalTokenRef,
		EndpointTokenRef:       config.ModalEndpointTokenRef,
		UserTransferMode:       req.UserTransferMode,
		BenchmarkTransferMode:  req.BenchmarkTransferMode,
		TemporaryThresholdMB:   req.TemporaryThresholdMB,
		ScaledownWindowSeconds: req.ScaledownWindowSeconds,
		MinContainers:          req.MinContainers,
		ModelCache:             req.ModelCache,
	})
	if req.TokenID != "" || req.TokenSecret != "" {
		if strings.TrimSpace(req.TokenID) == "" || strings.TrimSpace(req.TokenSecret) == "" {
			return notoapi.ModalStatus{}, notoapi.NewError(notoapi.CodeInvalidRequest, "both token_id and token_secret are required", nil)
		}
		if s.secrets == nil {
			return notoapi.ModalStatus{}, notoapi.NewError(notoapi.CodeInternal, "credential store is unavailable", nil)
		}
		if err := s.secrets.Set(ctx, m.TokenRef, req.TokenID+":"+req.TokenSecret); err != nil {
			return notoapi.ModalStatus{}, notoapi.NewError(notoapi.CodeInternal, err.Error(), nil)
		}
	}
	endpointToken := strings.TrimSpace(req.EndpointToken)
	if endpointToken == "" && m.EndpointURL != "" {
		endpointToken = randomHex(32)
	}
	if endpointToken != "" && s.secrets != nil {
		if err := s.secrets.Set(ctx, m.EndpointTokenRef, endpointToken); err != nil {
			return notoapi.ModalStatus{}, notoapi.NewError(notoapi.CodeInternal, err.Error(), nil)
		}
	}

	if err := s.updateCfg(func(cfg *config.Config) {
		cfg.Compute.Provider = modalProviderID
		cfg.Compute.Modal = mergeModalConfig(modalDefaults(cfg.Compute.Modal), m)
		if m.EndpointURL != "" {
			cfg.Compute.Modal.EndpointURL = m.EndpointURL
			cfg.Compute.Modal.DeploymentVersion = modalDesiredVersion
			cfg.Compute.Endpoint.URL = m.EndpointURL
			cfg.Compute.Endpoint.TokenRef = m.EndpointTokenRef
			if req.ConfigureRoutes {
				cfg.Compute.Speech.Location = config.ComputeLocationRemote
				cfg.Compute.Diarize.Location = config.ComputeLocationRemote
				cfg.Compute.Embed.Location = config.ComputeLocationLocal
			}
		}
	}); err != nil {
		return notoapi.ModalStatus{}, notoapi.NewError(notoapi.CodeInternal, err.Error(), nil)
	}
	return s.GetModalComputeStatus(ctx)
}

func (s *Service) RunModalBenchmark(ctx context.Context, req notoapi.ModalBenchmarkRequest) (notoapi.ModalBenchmarkResult, error) {
	if req.Suite == "" {
		req.Suite = "smoke@2026-06-18"
	}
	res, err := s.BenchRun(ctx, notoapi.BenchRunRequest{
		SuiteID:          req.Suite,
		Tier:             "smoke",
		OperatingMode:    "batch_queue",
		ExecutionProfile: "modal_cuda",
		BudgetUSDCap:     0.25,
	})
	if err != nil {
		return notoapi.ModalBenchmarkResult{}, err
	}
	return notoapi.ModalBenchmarkResult{
		Accepted: true,
		RunID:    res.RunID,
		Message:  fmt.Sprintf("bench run complete run_id=%s trace_valid=%v", res.RunID, res.TraceValid),
	}, nil
}

type credentialStatus struct {
	Configured bool
	Source     string
}

func (s *Service) secretStatus(ctx context.Context, ref string) (credentialStatus, error) {
	if s.secrets == nil || strings.TrimSpace(ref) == "" {
		return credentialStatus{Source: "missing"}, nil
	}
	st, err := s.secrets.Status(ctx, ref)
	if err != nil {
		return credentialStatus{Source: "missing"}, err
	}
	return credentialStatus{Configured: st.Configured, Source: st.Source}, nil
}

func modalDefaults(m config.ModalComputeConfig) config.ModalComputeConfig {
	if m.AppName == "" {
		m.AppName = config.DefaultModalAppName
	}
	if m.Environment == "" {
		m.Environment = config.DefaultModalEnvironment
	}
	if m.GPU == "" {
		m.GPU = config.DefaultModalGPU
	}
	if m.TokenRef == "" {
		m.TokenRef = config.ModalTokenRef
	}
	if m.EndpointTokenRef == "" {
		m.EndpointTokenRef = config.ModalEndpointTokenRef
	}
	if m.ModelVolume == "" {
		m.ModelVolume = config.DefaultModalModelVolume
	}
	if m.BenchmarkVolume == "" {
		m.BenchmarkVolume = config.DefaultModalBenchmarkVolume
	}
	if m.UserTransferMode == "" {
		m.UserTransferMode = config.DefaultModalUserTransferMode
	}
	if m.UserTransferMode == "direct" {
		m.UserTransferMode = "http"
	}
	if m.UserTransferMode == "volume" {
		m.UserTransferMode = "temporary"
	}
	if m.UserTransferMode != "http" && m.UserTransferMode != "temporary" && m.UserTransferMode != "permanent" {
		m.UserTransferMode = config.DefaultModalUserTransferMode
	}
	if m.BenchmarkTransferMode == "" {
		m.BenchmarkTransferMode = config.DefaultModalBenchmarkTransferMode
	}
	if m.BenchmarkTransferMode == "direct" {
		m.BenchmarkTransferMode = "http"
	}
	if m.BenchmarkTransferMode == "volume" {
		m.BenchmarkTransferMode = "permanent"
	}
	if m.BenchmarkTransferMode != "http" && m.BenchmarkTransferMode != "temporary" && m.BenchmarkTransferMode != "permanent" {
		m.BenchmarkTransferMode = config.DefaultModalBenchmarkTransferMode
	}
	if m.TemporaryThresholdMB <= 0 {
		m.TemporaryThresholdMB = config.DefaultModalTemporaryThresholdMB
	}
	if m.ScaledownWindowSeconds <= 0 {
		m.ScaledownWindowSeconds = config.DefaultModalScaledownWindow
	}
	if m.MinContainers < 0 {
		m.MinContainers = config.DefaultModalMinContainers
	}
	if m.ModelCache == "" {
		m.ModelCache = config.DefaultModalModelCache
	}
	if m.ModelCache != "volume" && m.ModelCache != "image" {
		m.ModelCache = config.DefaultModalModelCache
	}
	return m
}

func mergeModalConfig(base, next config.ModalComputeConfig) config.ModalComputeConfig {
	if next.AppName != "" {
		base.AppName = next.AppName
	}
	if next.Environment != "" {
		base.Environment = next.Environment
	}
	if next.GPU != "" {
		base.GPU = next.GPU
	}
	if next.EndpointURL != "" {
		base.EndpointURL = next.EndpointURL
	}
	if next.TokenRef != "" {
		base.TokenRef = next.TokenRef
	}
	if next.EndpointTokenRef != "" {
		base.EndpointTokenRef = next.EndpointTokenRef
	}
	if next.DeploymentVersion != "" {
		base.DeploymentVersion = next.DeploymentVersion
	}
	if next.ModelVolume != "" {
		base.ModelVolume = next.ModelVolume
	}
	if next.BenchmarkVolume != "" {
		base.BenchmarkVolume = next.BenchmarkVolume
	}
	if next.UserTransferMode != "" {
		base.UserTransferMode = next.UserTransferMode
	}
	if next.BenchmarkTransferMode != "" {
		base.BenchmarkTransferMode = next.BenchmarkTransferMode
	}
	if next.TemporaryThresholdMB > 0 {
		base.TemporaryThresholdMB = next.TemporaryThresholdMB
	}
	if next.ScaledownWindowSeconds > 0 {
		base.ScaledownWindowSeconds = next.ScaledownWindowSeconds
	}
	if next.MinContainers >= 0 {
		base.MinContainers = next.MinContainers
	}
	if next.ModelCache != "" {
		base.ModelCache = next.ModelCache
	}
	return base
}

func modalStatusMessage(ready bool, version string) string {
	if !ready {
		return "Modal credentials can be stored now; set endpoint_url after the Modal Web Function exists."
	}
	if version != "" && version != modalDesiredVersion {
		return "Modal endpoint is configured but should be updated to the current noto compute version."
	}
	return "Modal compute endpoint is configured; model weights should load from cache, while user audio uses the configured http/temporary/permanent transfer policy."
}

func randomHex(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return ""
	}
	return hex.EncodeToString(b)
}
